### ISSUE TITLE
Get pirateship to talk to the XMPP server

### ISSUE THREAD

**Issue by ajamesVISD** [ajamesVISD/pirateship#33]
[Babbler](http://sco0ter.bitbucket.org/babbler/index.html) is the library we're trying.

The branch to work on is "speaktoXMPP."

We want pirateship to  be a presence on the XMPP server, so that any of us can talk to it. First just have it say "hello" back, or just echo whatever is said to it.

I think we want to use the [command pattern](https://en.wikipedia.org/wiki/Command_pattern#Java) in how we set this up. It is not an easy pattern to understand, so take your time.

**Comment by tristanishappy** [comment]
Gabriello is working on this

**Comment by ajamesVISD** [comment]
A part of the puzzle:

The Babbler client needs to announce its presence:

``` java
xmppClient.send(new Presence(Presence.Show.AWAY));
```

From [this page](http://sco0ter.bitbucket.org/babbler/basics.html)
