### ISSUE TITLE
An Events generator

### ISSUE THREAD

**Issue by ajamesVISD** [ajamesVISD/pirateship#4]
Connor has an Events class to play with. Now let's practice having random Events appear sometimes at the moment when the Player enters a Location.

For this we need a Randomizer. Have it generate certain events randomly. Don't worry about making a table of odds or anything; just have it kick up a random event for each Location.

You'll have to tinker with the Location class so that each one has a chance of having an Event in it. At first, set that chance to 100% so we can see the Events when we test out the system. Then we can try out smaller odds.

Once this works in this simple way, we can add more features.

**Comment by tristanishappy** [comment]
Conner claimed this
