### ISSUE TITLE
Message package needs to be created

### ISSUE THREAD

**Issue by ajamesVISD** [ajamesVISD/pirateship#5]
We are going to have messages in this world. We don't know everything about them. We know how much they could do, but let's start _very_ small.

Make a Message package, just as there is currently an IO package and a Structure package.

Create a Message class. Keep it _very_ simple: a message has a subject, and a text.

First, test making a new Message and setting its subject and text.

Then figure out how to get your message to appear at a Location, so that when the player enters that Location, it says "There is a message for you!" Don't worry about how to have the player read the message or mark it as read. Just have it appear in the Location and print itself to the screen immediately.

We will add other features later.

**Comment by goliaro** [comment]
claimed
