### ISSUE TITLE
"Anytime" commands

### ISSUE THREAD

**Issue by ajamesVISD** [ajamesVISD/pirateship#6]
Certain commands work only in certain places. "East" only works in Locations with a Route that is keyed to the accessor "east."

Some commands should work anywhere. Laurel provided the excellent example of "dance": Anywhere, anytime, if you type "dance," something should happen.

Later, we may want to key these commands to different systems. For instance, "shout" may do something to our messaging system; "inventory" may open our inventory, and so on.

For now, just have a set of commands that write to or read from our I/O to make something happen.

**Comment by laurelgothub** [comment]
claimed
