### ISSUE TITLE
Add Regions class so Locations can belong to a Region

### ISSUE THREAD

**Issue by ajamesVISD** [ajamesVISD/pirateship#9]
Say we want it to rain on Westmost Island. There is no one location called "Westmost Island." There's a Crystal Bay and a Beach Hut and a Solemn Cave and so forth, all of which are Locations. But there is no Location called "Westmost Island."

Why not? Well, where are you standing when you stand on "Westmost Island." What description does the Player receive? It depends on what Location in the island you have arrived at. You can see, and be in, the Location directly. But you can't just be in the Island.

Let's think of an analogy. You travel through Asia. What does it look like when you arrive in Asia. "You see Asia. It looks so huge! You see 18 countries..." No, you arrive in an airport in Seoul, or a beach in Thailand, or a platform on a train station in Tokyo. Now you can look around and describe what you see.

So instead of your location being "Westmost Island," it's a specific location in Westmost Island. That's fine. _But_, suppose that:
- We want a typhoon to hit Westmost Island. All over Westmost Island you hear roaring wind and feel the lashing raindrops and so forth.
- The Player claims Westmost Island as friendly territory (whatever that means).
- A booming voice from the sky speaks to everyone on Westmost Island.
- Westmost Island is sinking into the sea! Everybody head for the boats!

And so forth. Clearly we need to know which locations are in Westmost Island.

So, why not have Locations have Locations in them? Keep an ArrayList of sublocations within Locations. But Westmost Island doesn't behave like a Location at all. There are no routes to and from it. A Player can't have Westmost Island as its Location. Westmost Island can't have Items in it. And so forth.

So let's call Westmost Island a Region. Remember, this whole system can make any geographic-type system you want. So "Chat Rooms" can be a Region.

Regions need to be able to:
- Send Events to Locations within them (how those Locations handle those Events can be up to them).
- Send Messages to Locations within them (when the Message class is created).
- "Know," via the Locations, which players are in that Region.
- Call public methods on Locations within the Region. So if Locations have public Lock() or RainMoney() methods, the Region can invoke those. For instance, the "Chat Rooms" region can close all the boards within it.

Notice that Locations do not have to connected via Routes to belong to a Region. If you want to declare that every picnic table is a Region, all the picnic tables can be all over the game world. You can still use the AllPicnicTables region to send cornbread to every picnic table.

So: Create a Region class. Keep it simple. Change the Location class so each location can be part of **one or more** regions. Then use the Region class to make something change about the Locations within it.

**Comment by gabrieleoliaro** [comment]
claimed
